/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import modelo.Docentes;
/**
 *
 * @author Cristian
 */
public class frm_docente extends javax.swing.JFrame {

    /**
     * Creates new form frm_docente
     */
    Docentes obj_docentes;
    public frm_docente() {
        
        initComponents();
        obj_docentes =  new Docentes();
        tbl_docentes.setModel(obj_docentes.leer());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_nit = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_nombres = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_apellidos = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_Direccion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_telefono = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_fn = new javax.swing.JTextField();
        btn_aceptar = new javax.swing.JButton();
        btn_modificar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_docentes = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        lbl_id = new javax.swing.JLabel();
        btn_eliminar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_fn1 = new javax.swing.JTextField();
        txt_docentes = new javax.swing.JTextField();
        txt_ingresoregistro = new javax.swing.JTextField();
        txt_salario = new javax.swing.JTextField();
        txt_ingresolaboral = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Fira Code", 1, 14)); // NOI18N
        jLabel1.setText("Nit");

        txt_nit.setBackground(new java.awt.Color(210, 255, 114));
        txt_nit.setFont(new java.awt.Font("Fira Code", 0, 14)); // NOI18N
        txt_nit.setForeground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Fira Code", 1, 14)); // NOI18N
        jLabel2.setText("Nombres");

        txt_nombres.setBackground(new java.awt.Color(210, 255, 114));
        txt_nombres.setFont(new java.awt.Font("Fira Code", 0, 14)); // NOI18N
        txt_nombres.setForeground(new java.awt.Color(0, 0, 0));
        txt_nombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombresActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Fira Code", 1, 14)); // NOI18N
        jLabel3.setText("Apellidos");

        txt_apellidos.setBackground(new java.awt.Color(210, 255, 114));
        txt_apellidos.setFont(new java.awt.Font("Fira Code", 0, 14)); // NOI18N
        txt_apellidos.setForeground(new java.awt.Color(0, 0, 0));

        jLabel4.setFont(new java.awt.Font("Fira Code", 1, 14)); // NOI18N
        jLabel4.setText("Direccion");

        txt_Direccion.setBackground(new java.awt.Color(210, 255, 114));
        txt_Direccion.setFont(new java.awt.Font("Fira Code", 0, 14)); // NOI18N
        txt_Direccion.setForeground(new java.awt.Color(0, 0, 0));

        jLabel5.setFont(new java.awt.Font("Fira Code", 1, 14)); // NOI18N
        jLabel5.setText("Telefono");

        txt_telefono.setBackground(new java.awt.Color(210, 255, 114));
        txt_telefono.setFont(new java.awt.Font("Fira Code", 0, 14)); // NOI18N
        txt_telefono.setForeground(new java.awt.Color(0, 0, 0));

        jLabel6.setFont(new java.awt.Font("Fira Code", 1, 14)); // NOI18N
        jLabel6.setText("Fecha Nacimiento");

        txt_fn.setBackground(new java.awt.Color(210, 255, 114));
        txt_fn.setFont(new java.awt.Font("Fira Code", 0, 14)); // NOI18N
        txt_fn.setForeground(new java.awt.Color(0, 0, 0));

        btn_aceptar.setBackground(new java.awt.Color(21, 110, 226));
        btn_aceptar.setFont(new java.awt.Font("Fira Code", 1, 14)); // NOI18N
        btn_aceptar.setForeground(new java.awt.Color(255, 255, 255));
        btn_aceptar.setText("Agregar");
        btn_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptarActionPerformed(evt);
            }
        });

        btn_modificar.setBackground(new java.awt.Color(255, 175, 69));
        btn_modificar.setFont(new java.awt.Font("Fira Code", 1, 14)); // NOI18N
        btn_modificar.setForeground(new java.awt.Color(255, 255, 255));
        btn_modificar.setText("Actualizar");
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(108, 115, 61));
        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        tbl_docentes.setBackground(new java.awt.Color(255, 255, 255));
        tbl_docentes.setForeground(new java.awt.Color(0, 0, 0));
        tbl_docentes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_docentes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_docentesMouseClicked(evt);
            }
        });
        tbl_docentes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbl_docentesKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_docentes);

        jLabel7.setFont(new java.awt.Font("Fira Code", 1, 14)); // NOI18N
        jLabel7.setText("id");

        lbl_id.setFont(new java.awt.Font("Fira Code", 1, 14)); // NOI18N
        lbl_id.setText("0");

        btn_eliminar.setBackground(new java.awt.Color(199, 37, 62));
        btn_eliminar.setFont(new java.awt.Font("Fira Code", 1, 14)); // NOI18N
        btn_eliminar.setForeground(new java.awt.Color(255, 255, 255));
        btn_eliminar.setText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Fira Code", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(21, 179, 146));
        jLabel8.setText("FORMULARIO DOCENTES");

        jLabel9.setFont(new java.awt.Font("Fira Code", 1, 14)); // NOI18N
        jLabel9.setText("Codigo Docentes");

        jLabel10.setFont(new java.awt.Font("Fira Code", 1, 14)); // NOI18N
        jLabel10.setText("Fecha Ingreso Registros ");

        jLabel11.setFont(new java.awt.Font("Fira Code", 1, 14)); // NOI18N
        jLabel11.setText("Salario");

        jLabel12.setFont(new java.awt.Font("Fira Code", 1, 14)); // NOI18N
        jLabel12.setText("Fecha Ingreso Laboral ");

        txt_fn1.setBackground(new java.awt.Color(143, 191, 191));
        txt_fn1.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        txt_fn1.setForeground(new java.awt.Color(13, 13, 13));

        txt_docentes.setBackground(new java.awt.Color(210, 255, 114));
        txt_docentes.setFont(new java.awt.Font("Fira Code", 0, 14)); // NOI18N
        txt_docentes.setForeground(new java.awt.Color(0, 0, 0));

        txt_ingresoregistro.setBackground(new java.awt.Color(210, 255, 114));
        txt_ingresoregistro.setFont(new java.awt.Font("Fira Code", 0, 14)); // NOI18N
        txt_ingresoregistro.setForeground(new java.awt.Color(0, 0, 0));
        txt_ingresoregistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ingresoregistroActionPerformed(evt);
            }
        });

        txt_salario.setBackground(new java.awt.Color(210, 255, 114));
        txt_salario.setFont(new java.awt.Font("Fira Code", 0, 14)); // NOI18N
        txt_salario.setForeground(new java.awt.Color(0, 0, 0));

        txt_ingresolaboral.setBackground(new java.awt.Color(210, 255, 114));
        txt_ingresolaboral.setFont(new java.awt.Font("Fira Code", 0, 14)); // NOI18N
        txt_ingresolaboral.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(321, 321, 321)
                .addComponent(jLabel8)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txt_nombres, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_id, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_nit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_fn, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_docentes, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_salario, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_ingresolaboral)
                            .addComponent(txt_ingresoregistro, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(86, 86, 86))
            .addGroup(layout.createSequentialGroup()
                .addGap(347, 347, 347)
                .addComponent(btn_aceptar)
                .addGap(18, 18, 18)
                .addComponent(btn_modificar)
                .addGap(18, 18, 18)
                .addComponent(btn_eliminar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(175, 175, 175)
                    .addComponent(txt_fn1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(641, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lbl_id))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txt_nit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_nombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_fn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txt_docentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txt_salario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txt_ingresolaboral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(txt_ingresoregistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_modificar)
                    .addComponent(btn_aceptar)
                    .addComponent(btn_eliminar))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(424, 424, 424)
                    .addComponent(txt_fn1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(351, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombresActionPerformed

    private void btn_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptarActionPerformed

    if (txt_nit.getText().isEmpty() || txt_nombres.getText().isEmpty() || txt_apellidos.getText().isEmpty() ||
        txt_Direccion.getText().isEmpty() || txt_telefono.getText().isEmpty() || txt_fn.getText().isEmpty() ||
        txt_docentes.getText().isEmpty() || txt_salario.getText().isEmpty() || 
        txt_ingresolaboral.getText().isEmpty() || txt_ingresoregistro.getText().isEmpty()) {
        throw new IllegalArgumentException("Todos los campos deben ser llenados.");
    }
    
    Docentes obj_docentes = new Docentes();
    obj_docentes.setNit(txt_nit.getText());
    obj_docentes.setNombres(txt_nombres.getText());
    obj_docentes.setApellidos(txt_apellidos.getText());
    obj_docentes.setDireccion(txt_Direccion.getText());
    obj_docentes.setTelefono(txt_telefono.getText());
    obj_docentes.setFecha_nacimiento(txt_fn.getText());
    obj_docentes.setCodigo_docentes(txt_docentes.getText());
    
    try {
        double salario = Double.parseDouble(txt_salario.getText());
        obj_docentes.setSalario(salario);
    } catch (NumberFormatException e) {
        throw new IllegalArgumentException("Formato de salario invalido.");
    }
    
    obj_docentes.setFecha_ingreso_laborar(txt_ingresolaboral.getText());
    obj_docentes.setFecha_ingreso_registro(txt_ingresoregistro.getText());

    obj_docentes.agregar();

    tbl_docentes.setModel(obj_docentes.leer());
    
        
    }//GEN-LAST:event_btn_aceptarActionPerformed

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed
            // TODO add your handling code here:
        obj_docentes = new Docentes(
            Integer.parseInt(lbl_id.getText()),
            txt_nit.getText(),
            txt_nombres.getText(),
            txt_apellidos.getText(),
            txt_Direccion.getText(),
            txt_telefono.getText(),
            txt_fn.getText(),
            txt_docentes.getText(),
            Double.parseDouble(txt_salario.getText()),
            txt_ingresolaboral.getText(),
            txt_ingresoregistro.getText()
            );

            obj_docentes.modificar();
            tbl_docentes.setModel(obj_docentes.leer());
    }//GEN-LAST:event_btn_modificarActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1MouseClicked
    
    public void selec_datos(){
    int fila = tbl_docentes.getSelectedRow();
    
    lbl_id.setText(tbl_docentes.getValueAt(fila, 0).toString());
    txt_nit.setText(tbl_docentes.getValueAt(fila, 1).toString());
    txt_nombres.setText(tbl_docentes.getValueAt(fila, 2).toString());
    txt_apellidos.setText(tbl_docentes.getValueAt(fila, 3).toString());
    txt_Direccion.setText(tbl_docentes.getValueAt(fila, 4).toString());
    txt_telefono.setText(tbl_docentes.getValueAt(fila, 5).toString());
    txt_fn.setText(tbl_docentes.getValueAt(fila, 6).toString());

    // Nuevos campos:
    txt_docentes.setText(tbl_docentes.getValueAt(fila, 7).toString());
    txt_salario.setText(tbl_docentes.getValueAt(fila, 8).toString());
    txt_ingresolaboral.setText(tbl_docentes.getValueAt(fila, 9).toString());
    txt_ingresoregistro.setText(tbl_docentes.getValueAt(fila, 10).toString());
}

    private void tbl_docentesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbl_docentesKeyReleased
        // TODO add your handling code here:
        selec_datos();
    }//GEN-LAST:event_tbl_docentesKeyReleased

    private void tbl_docentesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_docentesMouseClicked
        // TODO add your handling code here:
        selec_datos();
    }//GEN-LAST:event_tbl_docentesMouseClicked

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        // TODO add your handling code here:
       
        obj_docentes = new Docentes();
        obj_docentes.setId(Integer.parseInt(lbl_id.getText()) );
        obj_docentes.eliminar();
        tbl_docentes.setModel(obj_docentes.leer());
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void txt_ingresoregistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ingresoregistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ingresoregistroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_docente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
 
        
         try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_docente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_aceptar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JTable tbl_docentes;
    private javax.swing.JTextField txt_Direccion;
    private javax.swing.JTextField txt_apellidos;
    private javax.swing.JTextField txt_docentes;
    private javax.swing.JTextField txt_fn;
    private javax.swing.JTextField txt_fn1;
    private javax.swing.JTextField txt_ingresolaboral;
    private javax.swing.JTextField txt_ingresoregistro;
    private javax.swing.JTextField txt_nit;
    private javax.swing.JTextField txt_nombres;
    private javax.swing.JTextField txt_salario;
    private javax.swing.JTextField txt_telefono;
    // End of variables declaration//GEN-END:variables
}
